### PR TITLE
fix: Handle uncaught fetch exception

### PR DESCRIPTION
**Pull request by frankieyan**
Closes https://github.com/Flagsmith/flagsmith-js-client/issues/249

When the local cache is populated or when default flags are provided, `flagsmith.init` does not reject if the call to edge proxy fails; however, an uncaught exception gets thrown which is difficult to catch in user code. This change allows the error to be caught within Flagsmith (logging `Exception fetching cached logs` when verbose mode is on).

### CODE REVIEW

**Comment by kyle-ssg** [comment]
Hmm I'm not sure I understand this, if we await the api call this makes the cache useless since awaiting flagsmith.init would block until the API returns a response?

**Comment by frankieyan** [comment]
> Hmm I'm not sure I understand this, if we await the api call this makes the cache useless since awaiting flagsmith.init would block until the API returns a response?

That's what I realized just now looking at the failed test. Nice catch! 👍

**Comment by frankieyan** [comment]
So the crux of the issue for us is that the thrown error can't be handled outside of Flagsmith.  It doesn't reject the promise returned from `init`, nor does it call `onError`. This triggers an unhandled exception and turns out is lighting up our Sentry.

As for the error itself, I don't think we're too interested in tracking or handling it as it's likely just due to network flake.

**Comment by kyle-ssg** [comment]
Yeah I think it should definitely call on error, so that'll need fixing. From what I understood it did since init is all wrapped in a try catch that calls onError

**Comment by kyle-ssg** [comment]
@frankieyan Could you check whether adjusting to the following works for you

```
   // We want to resolve init since we have cached flags
    this.getFlags().catch((err) => {
     throw err // triggers call to onError
   });
```

**Comment by frankieyan** [comment]
> @frankieyan Could you check whether adjusting to the following works for you
> 
> ```
>    // We want to resolve init since we have cached flags
>     this.getFlags().catch((err) => {
>      throw err // triggers call to onError
>    });
> ```

@kyle-ssg no, that still results in the floating promise being rejected. Looks like calling onError explicitly works though.

If this approach looks good to you, I'll come back tomorrow and add a test case for when it calls `/identities/` as well, as I believe right now the new test cases are only hitting `/flags`.

**Comment by kyle-ssg** [comment]
Ok yep that works for me - let's go with that

**Comment by matthewelwell** [comment]
@frankieyan , just checking in to see if you're still able to add the test case as discussed with @kyle-ssg above?

**Comment by frankieyan** [comment]
Hey @matthewelwell! I've been a bit swamped recently but aiming to come back to it next week 👍

**Comment by gnapse** [comment]
@matthewelwell I'm helping Frankie on this one. Can you review the last commit and see if this is what's needed?

**Review by kyle-ssg — APPROVED** [review]

**Comment by gnapse** [comment]
Hey folks, when will there be a new release? One that includes this fix? cc @kyle-ssg @matthewelwell 

Hopefully, can we expect one before the end of the year?

**Comment by matthewelwell** [comment]
Hey @gnapse, yes, definitely! We have been stuck regarding releases due to matters outside of our control for a couple of weeks, but that should cease to be the case as of Thursday this week. Thanks for the patience, and apologies for the lack of communication on this.

**Comment by gnapse** [comment]
No worries. Thanks for the info. Good luck on Thursday! 🤞

**Pull request merged**
