### PR TITLE
Fix: Keep identity identifier in handleResponse

### LINKED ISSUE #262: `getFlags` removes identity identifier in evaluation context
In the current flagsmith version 7.0.1 the identity identifier gets reset within the `getFlags` backend call:

Image

1. log is during init -> the identifier is set
2. log is after `getFlags` / init backend call -> identifier is lost in evaluation context

This results in `setContext` to fail because the identifier is missing:

Image

### PR DESCRIPTION
**Pull request by jhoermann**
Fixes #262

### CODE REVIEW

**Comment by jhoermann** [comment]
Would be good to add a regression test I guess.

**Comment by jhoermann** [comment]
Needs to be verified if it solves the issue.

**Comment by matthewelwell** [comment]
Great, thanks for submitting this @jhoermann . The changes looks sound to me, but I'll wait for the test(s) before approving.

**Comment by jhoermann** [comment]
Should I still continue with the PR as its now fixed by the backend @matthewelwell?

**Comment by khvn26** [comment]
Now that the APIs are correctly honouring the contract, I believe adding any assumptions client-side would be redundant.

**Comment by jhoermann** [comment]
Got it.

**Review by matthewelwell — APPROVED** [review]

**Comment by Kisama** [comment]
Is there any update for this? I have a same issue on my client side like https://github.com/Flagsmith/flagsmith-js-client/issues/269

**Pull request merged**
